name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: geovanniandrade
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: output
          create_branch: true
          commit_message: "generate snake"
          file_pattern: dist/*
